Implemented multiple hostAliases entries
dell/csm-replication pull request #33
Opened 2022-04-12 10:15 UTC by IliaRN

# Description
Added the ability to add multiple hostAliases entries

# How Has This Been Tested?

Manually in real env

2022-04-12 10:32 UTC, maxan98 commented on helm/csm-replication/values.yaml
>  hostAliases:
This should be pre-commented in sample values file

2022-04-12 10:46 UTC, AronAtDell commented on helm/csm-replication/templates/controller.yaml
> +        name: configmap-volume
No newline eof.

2022-04-12 10:46 UTC, AronAtDell commented on helm/csm-replication/values.yaml
> +      - "foo.baz"
No newline eof.

2022-04-12 10:47 UTC, AronAtDell submitted a review, later dismissed
Apart from my comments, everything else looks good. Thanks!

2022-04-12 11:19 UTC, maxan98 approved these changes

2022-04-12 13:18 UTC, AronAtDell approved these changes

2022-04-12 16:26 UTC, walker2 requested changes
We should make corresponding changes to documentation to not forget about that later, please make the changes and link to them in this PR

2022-04-13 12:53 UTC, walker2 approved these changes

2022-04-13 12:54 UTC, merged